version: '3.8'

services:

  db:
    image: postgres
    volumes:
    - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword12345

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db-data:
  driver: local