version: '3.8'

services:

  db:
    image: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: marla
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword12345
    networks:
      - front-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - front-network      

volumes:
  postgresql_data:
    driver: local

networks:
  front-network:
    driver: bridge